import type { Locale } from "./i18n";
import { isLanguageCode, LANGUAGES, type LanguageCode } from "./settings";

/**
 * Textos de la web pública en español e inglés (tarea 2.5). Los textos del catálogo (nombres de
 * producto, entradas, punto de encuentro) vienen de la BD tal cual.
 */

const ES = {
  languageLabel: "Idioma",
  switchTo: "English version",
  homeTitle: "Experiencias en Tenerife",
  homeIntro: "Grupos reducidos, guías locales y cancelación gratuita.",
  from: "Desde",
  noProducts: "No hay experiencias a la venta.",
  experiences: "Experiencias",
  details: "Detalles",
  maxPeople: (capacity: number) => `Máx. ${capacity} personas`,
  hotelPickup: "Recogida en hotel",
  meetingPoint: "Punto de encuentro",
  freeCancellation: (hours: number) => `Cancelación gratuita hasta ${hours} h antes.`,
  bookNow: "Reserva ahora y asegura tu plaza.",
  book: "Reservar",
  previousMonth: "Mes anterior",
  nextMonth: "Mes siguiente",
  dayFrom: (price: string) => `, desde ${price}`,
  noDates: "No hay fechas disponibles ahora mismo.",
  timesOn: (day: string) => `Horarios del ${day}`,
  chooseDay: "Elige un día disponible.",
  seatsLeft: (free: number) => (free === 1 ? "¡Queda 1!" : `¡Quedan ${free}!`),
  seats: (free: number) => `${free} plazas`,
  tickets: "Entradas",
  removeTicket: (name: string) => `Quitar ${name}`,
  addTicket: (name: string) => `Añadir ${name}`,
  ticketQty: (name: string) => `${name}: cantidad`,
  onlyLeft: (free: number) => (free === 1 ? "Solo queda 1 plaza en esta salida." : `Solo quedan ${free} plazas en esta salida.`),
  groupLimit: (max: number) => `Por la web puedes reservar hasta ${max} plazas. Para grupos, llámanos.`,
  total: "Total",
  continue: "Continuar",
  checkoutTitle: "Completa tu reserva",
  checkTickets: "Revisa tus entradas",
  sessionGone: "Esta salida ya no está disponible",
  sessionGoneText: "Puede que se haya completado o que ya no se venda por la web. Elige otro horario.",
  backTo: (name: string) => `Volver a ${name}`,
  change: "Cambiar",
  yourBooking: "Tu reserva",
  fullName: "Nombre y apellidos",
  email: "Email",
  phone: "Teléfono",
  pickupHotel: "Hotel de recogida",
  optional: "(opcional)",
  hotelPlaceholder: (meetingPoint: string) =>
    meetingPoint ? `Si lo dejas vacío: ${meetingPoint}` : "Si lo dejas vacío, punto de encuentro",
  trapLabel: "No rellenes este campo",
  payOnTheDay: "Pagas el día de la excursión",
  payOnTheDayText: "Reservas ahora sin pagar nada y abonas el total al guía antes de salir.",
  booking: "Reservando…",
  confirmBooking: (total: string) => `Confirmar reserva · ${total}`,
  privacy: "Usamos tus datos solo para gestionar esta reserva y avisarte si hay cambios.",
  confirmedTitle: "Reserva confirmada",
  confirmedHeading: "¡Reserva confirmada!",
  cancelledHeading: "Reserva cancelada",
  keepCode: "Apunta este código o haz una captura: te lo pedirán el día de la excursión.",
  bookingCode: "Código de reserva",
  cancelled: "Cancelada",
  paid: "Pagada",
  payThere: "Pagas allí",
  pickupAt: (hotel: string) => `Recogida en ${hotel}`,
  payTotalOnTheDay: "Pagas el total el día de la excursión.",
  freeCancellationBeforeStart: (hours: number) => `Cancelación gratuita hasta ${hours} h antes de la salida.`,
  callForChanges: (phone: string) => `Para cambios o cancelaciones, llama al ${phone}.`,
  backHome: "Volver a la web",
  errors: {
    generic: "No se pudo completar la reserva. Inténtalo de nuevo en unos minutos.",
    genericShort: "No se pudo completar la reserva.",
    badTickets: "Revisa las entradas elegidas.",
    priceChanged: "El precio ha cambiado. Vuelve a elegir las entradas para ver el total actualizado.",
    tooMany: "Has hecho varias reservas seguidas. Inténtalo más tarde o llámanos.",
    ticketGone: "Alguna de las entradas ya no se vende. Vuelve a elegirlas.",
    noSeatTicket: "Añade al menos una entrada con plaza.",
    justSoldOut: "Lo sentimos: esta salida se acaba de completar. Elige otro horario.",
    removeSome: (free: number) =>
      `Solo ${free === 1 ? "queda 1 plaza" : `quedan ${free} plazas`} en esta salida. Quita alguna entrada.`,
    notEnoughSeats: "No quedan plazas suficientes en esta salida.",
    notBookable: "Esta salida ya no admite reservas. Elige otro horario.",
    name: "Escribe tu nombre y apellidos.",
    nameTooLong: "El nombre es demasiado largo.",
    email: "Revisa el email: no parece válido.",
    phoneTooLong: "El teléfono es demasiado largo.",
    phoneChars: "El teléfono solo puede tener números, espacios y + ( ) - .",
    hotelTooLong: "El nombre del hotel es demasiado largo.",
  },
  languages: LANGUAGES as Record<LanguageCode, string>,
};

export type WebText = typeof ES;

const EN: WebText = {
  languageLabel: "Language",
  switchTo: "Versión en español",
  homeTitle: "Experiences in Tenerife",
  homeIntro: "Small groups, local guides and free cancellation.",
  from: "From",
  noProducts: "No experiences on sale right now.",
  experiences: "Experiences",
  details: "Details",
  maxPeople: (capacity) => `Max. ${capacity} people`,
  hotelPickup: "Hotel pickup",
  meetingPoint: "Meeting point",
  freeCancellation: (hours) => `Free cancellation up to ${hours} h before.`,
  bookNow: "Book now and secure your spot.",
  book: "Book",
  previousMonth: "Previous month",
  nextMonth: "Next month",
  dayFrom: (price) => `, from ${price}`,
  noDates: "No dates available right now.",
  timesOn: (day) => `Times on ${day}`,
  chooseDay: "Choose an available day.",
  seatsLeft: (free) => `${free} left!`,
  seats: (free) => `${free} spots`,
  tickets: "Tickets",
  removeTicket: (name) => `Remove ${name}`,
  addTicket: (name) => `Add ${name}`,
  ticketQty: (name) => `${name}: quantity`,
  onlyLeft: (free) => (free === 1 ? "Only 1 spot left on this tour." : `Only ${free} spots left on this tour.`),
  groupLimit: (max) => `You can book up to ${max} spots online. For groups, give us a call.`,
  total: "Total",
  continue: "Continue",
  checkoutTitle: "Complete your booking",
  checkTickets: "Check your tickets",
  sessionGone: "This tour is no longer available",
  sessionGoneText: "It may be full or no longer sold online. Please choose another time.",
  backTo: (name) => `Back to ${name}`,
  change: "Change",
  yourBooking: "Your booking",
  fullName: "Full name",
  email: "Email",
  phone: "Phone",
  pickupHotel: "Pickup hotel",
  optional: "(optional)",
  hotelPlaceholder: (meetingPoint) => (meetingPoint ? `If left empty: ${meetingPoint}` : "If left empty, the meeting point"),
  trapLabel: "Do not fill in this field",
  payOnTheDay: "Pay on the day of the tour",
  payOnTheDayText: "Book now without paying anything and pay the full amount to your guide before departure.",
  booking: "Booking…",
  confirmBooking: (total) => `Confirm booking · ${total}`,
  privacy: "We only use your details to manage this booking and to let you know about any changes.",
  confirmedTitle: "Booking confirmed",
  confirmedHeading: "Booking confirmed!",
  cancelledHeading: "Booking cancelled",
  keepCode: "Write down this code or take a screenshot: you will be asked for it on the day of the tour.",
  bookingCode: "Booking code",
  cancelled: "Cancelled",
  paid: "Paid",
  payThere: "Pay there",
  pickupAt: (hotel) => `Pickup at ${hotel}`,
  payTotalOnTheDay: "You pay the full amount on the day of the tour.",
  freeCancellationBeforeStart: (hours) => `Free cancellation up to ${hours} h before departure.`,
  callForChanges: (phone) => `For changes or cancellations, call ${phone}.`,
  backHome: "Back to the website",
  errors: {
    generic: "We could not complete your booking. Please try again in a few minutes.",
    genericShort: "We could not complete your booking.",
    badTickets: "Please check the tickets you chose.",
    priceChanged: "The price has changed. Please choose your tickets again to see the updated total.",
    tooMany: "You have made several bookings in a row. Please try again later or call us.",
    ticketGone: "Some of the tickets are no longer sold. Please choose them again.",
    noSeatTicket: "Add at least one ticket with a seat.",
    justSoldOut: "Sorry: this tour has just sold out. Please choose another time.",
    removeSome: (free) => `Only ${free === 1 ? "1 spot" : `${free} spots`} left on this tour. Please remove some tickets.`,
    notEnoughSeats: "There are not enough spots left on this tour.",
    notBookable: "This tour no longer accepts bookings. Please choose another time.",
    name: "Please enter your full name.",
    nameTooLong: "The name is too long.",
    email: "Please check your email: it does not look valid.",
    phoneTooLong: "The phone number is too long.",
    phoneChars: "The phone number can only contain digits, spaces and + ( ) - .",
    hotelTooLong: "The hotel name is too long.",
  },
  languages: { es: "Spanish", en: "English", de: "German", fr: "French", it: "Italian", nl: "Dutch" },
};

const TEXTS: Record<Locale, WebText> = { es: ES, en: EN };

export function webText(locale: Locale): WebText {
  return TEXTS[locale];
}

/** Nombre del idioma de una salida («Inglés» / «English»); un código desconocido, en mayúsculas. */
export function languageName(code: string, locale: Locale): string {
  return isLanguageCode(code) ? TEXTS[locale].languages[code] : code.toUpperCase();
}
